### ISSUE TITLE
Problem Launching Franka_bringup

### ISSUE THREAD

**Issue by bk-poudel** [frankaemika/franka_ros2#146]
When, I try to run ros2 launch franka_bringup example.launch.py controller_name:=JointPositionExampleController

I get error, user@bibek-Lenovo-Slim-7-14IRP8:/ros2_ws$ ros2 launch franka_bringup example.launch.py controller_name:=JointPositionExampleController
[INFO] [launch]: All log files can be found below /home/user/.ros/log/2025-06-17-07-32-12-034125-bibek-Lenovo-Slim-7-14IRP8-22327
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [robot_state_publisher-1]: process started with pid [22328]
[INFO] [ros2_control_node-2]: process started with pid [22330]
[INFO] [joint_state_publisher-3]: process started with pid [22332]
[INFO] [spawner-4]: process started with pid [22334]
[INFO] [spawner-5]: process started with pid [22336]
[INFO] [spawner-6]: process started with pid [22338]
[ros2_control_node-2] [WARN] [1750145532.214497860] [NS_1.controller_manager]: [Deprecated] Passing the robot description parameter directly to the control_manager node is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.
[ros2_control_node-2] text not specified in the prefix tag
[ros2_control_node-2] text not specified in the arm_prefix tag
[ros2_control_node-2] [INFO] [1750145532.214901887] [resource_manager]: Loading hardware 'FrankaHardwareInterface' 
[ros2_control_node-2] [INFO] [1750145532.226858825] [resource_manager]: Initialize hardware 'FrankaHardwareInterface' 
[ros2_control_node-2] Parameter 'version' is not set. Please update your URDF (aka franka_description).
**_### [ros2_control_node-2] [FATAL] [1750145532.226993576] [FrankaHardwareInterface]: Parameter '' is not set. Please update your URDF (aka franka_description)._**
[ros2_control_node-2] [INFO] [1750145532.227013606] [resource_manager]: Failed to initialize hardware 'FrankaHardwareInterface'
[ros2_control_node-2] [WARN] [1750145532.227020894] [resource_manager]: System hardware component 'FrankaHardwareInterface' from plugin 'franka_hardware/FrankaHardwareInterface' failed to initialize.
[ros2_control_node-2] terminate called after throwing an instance of 'std::runtime_error'
[ros2_control_node-2]   what():  Wrong state or command interface configuration.
[ros2_control_node-2] missing state interfaces:
[ros2_control_node-2] ' fr3_joint1/position '   ' fr3_joint1/velocity ' ' fr3_joint1/effort '       ' fr3_joint2/position ' ' fr3_joint2/velocity ' ' fr3_joint2/effort '       ' fr3_joint3/position ' ' fr3_joint3/velocity ' ' fr3_joint3/effort '   ' fr3_joint4/position '     ' fr3_joint4/velocity ' ' fr3_joint4/effort '   ' fr3_joint5/position '     ' fr3_joint5/velocity ' ' fr3_joint5/effort '   ' fr3_joint6/position '     ' fr3_joint6/velocity ' ' fr3_joint6/effort '   ' fr3_joint7/position ' ' fr3_joint7/velocity '     ' fr3_joint7/effort '
[ros2_control_node-2] missing command interfaces:
[ros2_control_node-2] ' fr3_joint1/position '   ' fr3_joint1/velocity ' ' fr3_joint1/effort '       ' fr3_joint2/position ' ' fr3_joint2/velocity ' ' fr3_joint2/effort '       ' fr3_joint3/position ' ' fr3_joint3/velocity ' ' fr3_joint3/effort '   ' fr3_joint4/position '     ' fr3_joint4/velocity ' ' fr3_joint4/effort '   ' fr3_joint5/position '     ' fr3_joint5/velocity ' ' fr3_joint5/effort '   ' fr3_joint6/position '     ' fr3_joint6/velocity ' ' fr3_joint6/effort '   ' fr3_joint7/position ' ' fr3_joint7/velocity '     ' fr3_joint7/effort '
[ros2_control_node-2] Stack trace (most recent call last):
[ros2_control_node-2] #15   Object "", at 0xffffffffffffffff, in 
[ros2_control_node-2] #14   Object "/opt/ros/humble/lib/controller_manager/ros2_control_node", at 0x61314a039ee4, in 
[ros2_control_node-2] #13   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x702a25c32e3f, in __libc_start_main
[ros2_control_node-2] #12   Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x702a25c32d8f, in 
[ros2_control_node-2] #11   Object "/opt/ros/humble/lib/controller_manager/ros2_control_node", at 0x61314a0393e3, in 
[ros2_control_node-2] #10   Object "/opt/ros/humble/lib/libcontroller_manager.so", at 0x702a2634774a, in controller_manager::ControllerManager::ControllerManager(std::shared_ptr<rclcpp::Executor>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::NodeOptions const&)
[ros2_control_node-2] #9    Object "/opt/ros/humble/lib/libcontroller_manager.so", at 0x702a263426df, in controller_manager::ControllerManager::init_resource_manager(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[ros2_control_node-2] #8    Object "/opt/ros/humble/lib/libhardware_interface.so", at 0x702a25aff334, in hardware_interface::ResourceManager::load_urdf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)
[ros2_control_node-2] #7    Object "/opt/ros/humble/lib/libhardware_interface.so", at 0x702a25adb723, in 
[ros2_control_node-2] #6    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x702a25f004d7, in __cxa_throw
[ros2_control_node-2] #5    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x702a25f00276, in std::terminate()
[ros2_control_node-2] #4    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x702a25f0020b, in 
[ros2_control_node-2] #3    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x702a25ef4b9d, in 
[ros2_control_node-2] #2    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x702a25c317f2, in abort
[ros2_control_node-2] #1    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x702a25c4b475, in raise
[ros2_control_node-2] #0    Object "/usr/lib/x86_64-linux-gnu/libc.so.6", at 0x702a25c9f9fc, in pthread_kill
[ros2_control_node-2] Aborted (Signal sent by tkill() 22330 1000)
[robot_state_publisher-1] [INFO] [1750145532.239952783] [NS_1.robot_state_publisher]: got segment base
[robot_state_publisher-1] [INFO] [1750145532.240095184] [NS_1.robot_state_publisher]: got segment fr3_link0
[robot_state_publisher-1] [INFO] [1750145532.240110041] [NS_1.robot_state_publisher]: got segment fr3_link1
[robot_state_publisher-1] [INFO] [1750145532.240119925] [NS_1.robot_state_publisher]: got segment fr3_link2
[robot_state_publisher-1] [INFO] [1750145532.240128784] [NS_1.robot_state_publisher]: got segment fr3_link3
[robot_state_publisher-1] [INFO] [1750145532.240137215] [NS_1.robot_state_publisher]: got segment fr3_link4
[robot_state_publisher-1] [INFO] [1750145532.240145558] [NS_1.robot_state_publisher]: got segment fr3_link5
[robot_state_publisher-1] [INFO] [1750145532.240153757] [NS_1.robot_state_publisher]: got segment fr3_link6
[robot_state_publisher-1] [INFO] [1750145532.240161545] [NS_1.robot_state_publisher]: got segment fr3_link7
[robot_state_publisher-1] [INFO] [1750145532.240169493] [NS_1.robot_state_publisher]: got segment fr3_link8
[spawner-4] [INFO] [1750145532.505637628] [NS_1.spawner_joint_state_broadcaster]: waiting for service /NS_1/controller_manager/list_controllers to become available...
[spawner-5] [INFO] [1750145532.555416961] [NS_1.spawner_franka_robot_state_broadcaster]: waiting for service /NS_1/controller_manager/list_controllers to become available...
[spawner-6] [INFO] [1750145532.555417134] [NS_1.spawner_JointPositionExampleController]: waiting for service /NS_1/controller_manager/list_controllers to become available...
[ERROR] [ros2_control_node-2]: process has died [pid 22330, exit code -6, cmd '/opt/ros/humble/lib/controller_manager/ros2_control_node --ros-args -r __ns:=/NS_1 --params-file /ros2_ws/install/franka_bringup/share/franka_bringup/config/controllers.yaml --params-file /tmp/launch_params_wt6504wh --params-file /tmp/launch_params_j9axufr4'].
[INFO] [launch]: process[ros2_control_node-2] was required: shutting down launched system
[INFO] [spawner-6]: sending signal 'SIGINT' to process[spawner-6]
[INFO] [spawner-5]: sending signal 'SIGINT' to process[spawner-5]
[INFO] [spawner-4]: sending signal 'SIGINT' to process[spawner-4]
[INFO] [joint_state_publisher-3]: sending signal 'SIGINT' to process[joint_state_publisher-3]
[INFO] [robot_state_publisher-1]: sending signal 'SIGINT' to process[robot_state_publisher-1]
[joint_state_publisher-3] Traceback (most recent call last):
[joint_state_publisher-3]   File "/opt/ros/humble/lib/joint_state_publisher/joint_state_publisher", line 33, in <module>
[joint_state_publisher-3]     sys.exit(load_entry_point('joint-state-publisher==2.4.0', 'console_scripts', 'joint_state_publisher')())
[joint_state_publisher-3]   File "/opt/ros/humble/lib/python3.10/site-packages/joint_state_publisher/joint_state_publisher.py", line 463, in main
[joint_state_publisher-3]     jsp = JointStatePublisher(parsed_args.description_file)
[joint_state_publisher-3]   File "/opt/ros/humble/lib/python3.10/site-packages/joint_state_publisher/joint_state_publisher.py", line 266, in __init__
[joint_state_publisher-3]     super().__init__('joint_state_publisher', automatically_declare_parameters_from_overrides=True)
[joint_state_publisher-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 228, in __init__
[robot_state_publisher-1] [INFO] [1750145532.569476909] [rclcpp]: signal_handler(signum=2)
[joint_state_publisher-3]     self._parameter_service = ParameterService(self)
[joint_state_publisher-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/parameter_service.py", line 34, in __init__
[joint_state_publisher-3]     node.create_service(
[joint_state_publisher-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/node.py", line 1465, in create_service
[joint_state_publisher-3]     check_is_valid_srv_type(srv_type)
[joint_state_publisher-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/type_support.py", line 51, in check_is_valid_srv_type
[joint_state_publisher-3]     check_for_type_support(srv_type)
[joint_state_publisher-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/type_support.py", line 29, in check_for_type_support
[joint_state_publisher-3]     msg_or_srv_type.__class__.__import_type_support__()
[joint_state_publisher-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rcl_interfaces/srv/_describe_parameters.py", line 284, in __import_type_support__
[joint_state_publisher-3]     module = import_type_support('rcl_interfaces')
[joint_state_publisher-3]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rosidl_generator_py/import_type_support_impl.py", line 45, in import_type_support
[joint_state_publisher-3]     with add_dll_directories_from_env('PATH'):
[joint_state_publisher-3]   File "/usr/lib/python3.10/contextlib.py", line 281, in helper
[joint_state_publisher-3]     return _GeneratorContextManager(func, args, kwds)
[joint_state_publisher-3]   File "/usr/lib/python3.10/contextlib.py", line 106, in __init__
[joint_state_publisher-3]     doc = getattr(func, "__doc__", None)
[joint_state_publisher-3] KeyboardInterrupt
[ERROR] [joint_state_publisher-3]: process has died [pid 22332, exit code -2, cmd '/opt/ros/humble/lib/joint_state_publisher/joint_state_publisher --ros-args -r __node:=joint_state_publisher -r __ns:=/NS_1 --params-file /tmp/launch_params_19om_di_'].
[INFO] [robot_state_publisher-1]: process has finished cleanly [pid 22328]
[INFO] [spawner-6]: process has finished cleanly [pid 22338]
[INFO] [spawner-4]: process has finished cleanly [pid 22334]
[INFO] [spawner-5]: process has finished cleanly [pid 22336]
Any help is appreciated
I am using the docker Installation

**Comment by gomezgu** [comment]
Hi @bk-poudel,

The problem with franka_description should be solved as we released a new version today.

**Comment by VaRuN-2509** [comment]
I STILL GET THE SAME ERROR WITH THE NEW FRANKA_DESCRIPTION PKG CLONED


ros2 launch franka_fr3_moveit_config moveit.launch.py robot_ip:=dont-care use_fake_hardware:=192.168.1.11
[INFO] [launch]: All log files can be found below /home/v25/.ros/log/2025-06-25-15-56-58-377038-smart-OptiPlex-Tower-Plus-7020-16022
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executed command failed. Command: /opt/ros/humble/bin/xacro /home/v25/franka_ros2_ws/install/franka_description/share/franka_description/robots/fr3/fr3.urdf.xacro hand:=true robot_ip:=dont-care use_fake_hardware:=192.168.1.11 fake_sensor_commands:=false ros2_control:=true
Captured stderr output: error: Xacro conditional "${use_fake_hardware}" evaluated to "192.168.1.11", which is not a boolean expression.
when instantiating macro: franka_arm_ros2_control (/home/v25/franka_ros2_ws/install/franka_description/share/franka_description/robots/common/franka_arm.ros2_control.xacro)
instantiated from: franka_robot (/home/v25/franka_ros2_ws/install/franka_description/share/franka_description/robots/common/franka_robot.xacro)
in file: /home/v25/franka_ros2_ws/install/franka_description/share/franka_description/robots/fr3/fr3.urdf.xacro

v25@smart-OptiPlex-Tower-Plus-7020:~/franka_ros2_ws$ ros2 launch franka_fr3_moveit_config moveit.launch.py robot_ip:=192.168.1.11
[INFO] [launch]: All log files can be found below /home/v25/.ros/log/2025-06-25-15-57-16-997226-smart-OptiPlex-Tower-Plus-7020-16027
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rviz2-1]: process started with pid [16030]
[INFO] [robot_state_publisher-2]: process started with pid [16032]
[INFO] [move_group-3]: process started with pid [16034]
[INFO] [ros2_control_node-4]: process started with pid [16036]
[INFO] [joint_state_publisher-5]: process started with pid [16038]
[INFO] [spawner-6]: process started with pid [16040]
[INFO] [franka_gripper_node-7]: process started with pid [16042]
[INFO] [ros2-8]: process started with pid [16044]
[INFO] [ros2-9]: process started with pid [16046]
[ros2_control_node-4] [WARN] [1750847237.231939296] [controller_manager]: [Deprecated] Passing the robot description parameter directly to the control_manager node is deprecated. Use '~/robot_description' topic from 'robot_state_publisher' instead.
[ros2_control_node-4] text not specified in the prefix tag
[ros2_control_node-4] text not specified in the arm_prefix tag
[ros2_control_node-4] [INFO] [1750847237.232138112] [resource_manager]: Loading hardware 'FrankaHardwareInterface' 
[franka_gripper_node-7] [INFO] [1750847237.234975364] [franka_gripper]: Trying to establish a connection with the gripper
[franka_gripper_node-7] [INFO] [1750847237.235676508] [franka_gripper]: Connected to gripper
[ros2_control_node-4] [INFO] [1750847237.236366962] [resource_manager]: Initialize hardware 'FrankaHardwareInterface' 
[ros2_control_node-4] Parameter 'version' is not set. Please update your URDF (aka franka_description).
[ros2_control_node-4] [FATAL] [1750847237.236419842] [FrankaHardwareInterface]: Parameter '' is not set. Please update your URDF (aka franka_description).
[ros2_control_node-4] [INFO] [1750847237.236425740] [resource_manager]: Failed to initialize hardware 'FrankaHardwareInterface'
[ros2_control_node-4] [WARN] [1750847237.236427792] [resource_manager]: System hardware component 'FrankaHardwareInterface' from plugin 'franka_hardware/FrankaHardwareInterface' failed to initialize.
[ros2_control_node-4] terminate called after throwing an instance of 'std::runtime_error'
[ros2_control_node-4]   what():  Wrong state or command interface configuration.
[ros2_control_node-4] missing state interfaces:
[ros2_control_node-4] ' fr3_joint1/position '	' fr3_joint1/velocity '	' fr3_joint1/effort '	' fr3_joint2/position '	' fr3_joint2/velocity '	' fr3_joint2/effort '	' fr3_joint3/position '	' fr3_joint3/velocity '	' fr3_joint3/effort '	' fr3_joint4/position '	' fr3_joint4/velocity '	' fr3_joint4/effort '	' fr3_joint5/position '	' fr3_joint5/velocity '	' fr3_joint5/effort '	' fr3_joint6/position '	' fr3_joint6/velocity '	' fr3_joint6/effort '	' fr3_joint7/position '' fr3_joint7/velocity '	' fr3_joint7/effort '	
[ros2_control_node-4] missing command interfaces:
[ros2_control_node-4] ' fr3_joint1/position '	' fr3_joint1/velocity '	' fr3_joint1/effort '	' fr3_joint2/position '	' fr3_joint2/velocity '	' fr3_joint2/effort '	' fr3_joint3/position '	' fr3_joint3/velocity '	' fr3_joint3/effort '	' fr3_joint4/position '	' fr3_joint4/velocity '	' fr3_joint4/effort '	' fr3_joint5/position '	' fr3_joint5/velocity '	' fr3_joint5/effort '	' fr3_joint6/position '	' fr3_joint6/velocity '	' fr3_joint6/effort '	' fr3_joint7/position '' fr3_joint7/velocity '	' fr3_joint7/effort '	
[ros2_control_node-4] Stack trace (most recent call last):
[ros2_control_node-4] #15   Object "", at 0xffffffffffffffff, in 
[ros2_control_node-4] #14   Object "/opt/ros/humble/lib/controller_manager/ros2_control_node", at 0x5d1856cdfee4, in 
[move_group-3] [WARN] [1750847237.240958505] [move_group.move_group]: Falling back to using the the move_group node namespace (deprecated behavior).
[robot_state_publisher-2] [INFO] [1750847237.244593018] [robot_state_publisher]: got segment base
[robot_state_publisher-2] [INFO] [1750847237.244666268] [robot_state_publisher]: got segment fr3_hand
[robot_state_publisher-2] [INFO] [1750847237.244669874] [robot_state_publisher]: got segment fr3_hand_tcp
[robot_state_publisher-2] [INFO] [1750847237.244672127] [robot_state_publisher]: got segment fr3_leftfinger
[robot_state_publisher-2] [INFO] [1750847237.244674073] [robot_state_publisher]: got segment fr3_link0
[robot_state_publisher-2] [INFO] [1750847237.244675859] [robot_state_publisher]: got segment fr3_link1
[robot_state_publisher-2] [INFO] [1750847237.244677474] [robot_state_publisher]: got segment fr3_link2
[robot_state_publisher-2] [INFO] [1750847237.244679207] [robot_state_publisher]: got segment fr3_link3
[robot_state_publisher-2] [INFO] [1750847237.244680979] [robot_state_publisher]: got segment fr3_link4
[robot_state_publisher-2] [INFO] [1750847237.244682649] [robot_state_publisher]: got segment fr3_link5
[robot_state_publisher-2] [INFO] [1750847237.244684276] [robot_state_publisher]: got segment fr3_link6
[robot_state_publisher-2] [INFO] [1750847237.244685913] [robot_state_publisher]: got segment fr3_link7
[robot_state_publisher-2] [INFO] [1750847237.244687713] [robot_state_publisher]: got segment fr3_link8
[robot_state_publisher-2] [INFO] [1750847237.244689326] [robot_state_publisher]: got segment fr3_rightfinger
[move_group-3] [INFO] [1750847237.256528675] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0154799 seconds
[move_group-3] [INFO] [1750847237.256553486] [moveit_robot_model.robot_model]: Loading robot model 'fr3'...
[move_group-3] [WARN] [1750847237.256559111] [moveit_robot_model.robot_model]: Skipping virtual joint 'virtual_joint' because its child frame 'fr3_link0' does not match the URDF frame 'base'
[move_group-3] [INFO] [1750847237.256561488] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[move_group-3] [INFO] [1750847237.270293918] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Publishing maintained planning scene on 'monitored_planning_scene'
[move_group-3] [INFO] [1750847237.270387361] [moveit.ros_planning_interface.moveit_cpp]: Listening to 'joint_states' for joint states
[move_group-3] [INFO] [1750847237.270685803] [moveit_ros.current_state_monitor]: Listening to joint states on topic 'joint_states'
[move_group-3] [INFO] [1750847237.270795907] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/attached_collision_object' for attached collision objects
[move_group-3] [INFO] [1750847237.270802763] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting planning scene monitor
[move_group-3] [INFO] [1750847237.270867595] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to '/planning_scene'
[move_group-3] [INFO] [1750847237.270871933] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Starting world geometry update monitor for collision objects, attached objects, octomap updates.
[move_group-3] [INFO] [1750847237.270946349] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'collision_object'
[move_group-3] [INFO] [1750847237.271015310] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Listening to 'planning_scene_world' for planning scene world geometry
[move_group-3] [WARN] [1750847237.271104042] [moveit.ros.occupancy_map_monitor.middleware_handle]: Resolution not specified for Octomap. Assuming resolution = 0.1 instead
[move_group-3] [ERROR] [1750847237.271109288] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
[move_group-3] [INFO] [1750847237.271470571] [moveit.ros_planning_interface.moveit_cpp]: Loading planning pipeline 'move_group'
[ros2_control_node-4] #13   Source "../csu/libc-start.c", line 392, in __libc_start_main_impl [0x759833833e3f]
[ros2_control_node-4] #12   Source "../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main [0x759833833d8f]
[ros2_control_node-4] #11   Object "/opt/ros/humble/lib/controller_manager/ros2_control_node", at 0x5d1856cdf3e3, in 
[ros2_control_node-4] #10   Object "/opt/ros/humble/lib/libcontroller_manager.so", at 0x759833f5a74a, in controller_manager::ControllerManager::ControllerManager(std::shared_ptr<rclcpp::Executor>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rclcpp::NodeOptions const&)
[ros2_control_node-4] #9    Object "/opt/ros/humble/lib/libcontroller_manager.so", at 0x759833f556df, in controller_manager::ControllerManager::init_resource_manager(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[ros2_control_node-4] #8    Object "/opt/ros/humble/lib/libhardware_interface.so", at 0x759833700334, in hardware_interface::ResourceManager::load_urdf(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool)
[ros2_control_node-4] #7    Object "/opt/ros/humble/lib/libhardware_interface.so", at 0x7598336dc723, in 
[ros2_control_node-4] #6    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x759833b014d7, in __cxa_throw
[ros2_control_node-4] #5    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x759833b01276, in std::terminate()
[ros2_control_node-4] #4    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x759833b0120b, in 
[ros2_control_node-4] #3    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.30", at 0x759833af5b9d, in 
[ros2_control_node-4] #2    Source "./stdlib/abort.c", line 79, in abort [0x7598338327f2]
[ros2_control_node-4] #1    Source "../sysdeps/posix/raise.c", line 26, in raise [0x75983384c475]
[ros2_control_node-4] #0  | Source "./nptl/pthread_kill.c", line 89, in __pthread_kill_internal
[ros2_control_node-4]     | Source "./nptl/pthread_kill.c", line 78, in __pthread_kill_implementation
[ros2_control_node-4]       Source "./nptl/pthread_kill.c", line 44, in __pthread_kill [0x7598338a09fc]
[ros2_control_node-4] Aborted (Signal sent by tkill() 16036 1005)
[move_group-3] [INFO] [1750847237.276414678] [moveit.ros_planning.planning_pipeline]: Using planning interface 'OMPL'
[move_group-3] [INFO] [1750847237.277395022] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.path_tolerance' was not set. Using default value: 0.100000
[move_group-3] [INFO] [1750847237.277403997] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.resample_dt' was not set. Using default value: 0.100000
[move_group-3] [INFO] [1750847237.277406453] [moveit_ros.add_time_optimal_parameterization]: Param 'move_group.min_angle_change' was not set. Using default value: 0.001000
[move_group-3] [INFO] [1750847237.277415488] [moveit_ros.fix_workspace_bounds]: Param 'move_group.default_workspace_bounds' was not set. Using default value: 10.000000
[move_group-3] [INFO] [1750847237.277422715] [moveit_ros.fix_start_state_bounds]: Param 'move_group.start_state_max_bounds_error' was set to 0.100000
[move_group-3] [INFO] [1750847237.277424768] [moveit_ros.fix_start_state_bounds]: Param 'move_group.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-3] [INFO] [1750847237.277429476] [moveit_ros.fix_start_state_collision]: Param 'move_group.start_state_max_dt' was not set. Using default value: 0.500000
[move_group-3] [INFO] [1750847237.277431495] [moveit_ros.fix_start_state_collision]: Param 'move_group.jiggle_fraction' was not set. Using default value: 0.020000
[move_group-3] [INFO] [1750847237.277433452] [moveit_ros.fix_start_state_collision]: Param 'move_group.max_sampling_attempts' was not set. Using default value: 100
[move_group-3] [INFO] [1750847237.277438374] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Add Time Optimal Parameterization'
[move_group-3] [INFO] [1750847237.277440083] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Resolve constraint frames to robot links'
[move_group-3] [INFO] [1750847237.277441382] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Workspace Bounds'
[move_group-3] [INFO] [1750847237.277456880] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Bounds'
[move_group-3] [INFO] [1750847237.277458261] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State In Collision'
[move_group-3] [INFO] [1750847237.277459458] [moveit.ros_planning.planning_pipeline]: Using planning request adapter 'Fix Start State Path Constraints'
[move_group-3] [INFO] [1750847237.290497652] [moveit.plugins.moveit_simple_controller_manager]: Added FollowJointTrajectory controller for fr3_arm_controller
[move_group-3] [INFO] [1750847237.290518988] [moveit.plugins.moveit_simple_controller_manager]: Max effort set to 0.0
[move_group-3] [INFO] [1750847237.291148725] [moveit.plugins.moveit_simple_controller_manager]: Added GripperCommand controller for fr3_gripper
[move_group-3] [INFO] [1750847237.291221074] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-3] [INFO] [1750847237.291230561] [moveit.plugins.moveit_simple_controller_manager]: Returned 2 controllers in list
[move_group-3] [INFO] [1750847237.291443853] [moveit_ros.trajectory_execution_manager]: Trajectory execution is managing controllers
[move_group-3] [INFO] [1750847237.291450892] [move_group.move_group]: MoveGroup debug mode is ON
[move_group-3] [INFO] [1750847237.295907226] [move_group.move_group]: 
[move_group-3] 
[move_group-3] ********************************************************
[move_group-3] * MoveGroup using: 
[move_group-3] *     - ApplyPlanningSceneService
[move_group-3] *     - ClearOctomapService
[move_group-3] *     - CartesianPathService
[move_group-3] *     - ExecuteTrajectoryAction
[move_group-3] *     - GetPlanningSceneService
[move_group-3] *     - KinematicsService
[move_group-3] *     - MoveAction
[move_group-3] *     - MotionPlanService
[move_group-3] *     - QueryPlannersService
[move_group-3] *     - StateValidationService
[move_group-3] ********************************************************
[move_group-3] 
[move_group-3] [INFO] [1750847237.295928196] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[move_group-3] [INFO] [1750847237.295932491] [moveit_move_group_capabilities_base.move_group_context]: MoveGroup context initialization complete
[move_group-3] Loading 'move_group/ApplyPlanningSceneService'...
[move_group-3] Loading 'move_group/ClearOctomapService'...
[move_group-3] Loading 'move_group/MoveGroupCartesianPathService'...
[move_group-3] Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-3] Loading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-3] Loading 'move_group/MoveGroupKinematicsService'...
[move_group-3] Loading 'move_group/MoveGroupMoveAction'...
[move_group-3] Loading 'move_group/MoveGroupPlanService'...
[move_group-3] Loading 'move_group/MoveGroupQueryPlannersService'...
[move_group-3] Loading 'move_group/MoveGroupStateValidationService'...
[move_group-3] 
[move_group-3] You can start planning now!
[move_group-3] 
[spawner-6] [INFO] [1750847237.361421893] [spawner_franka_robot_state_broadcaster]: waiting for service /controller_manager/list_controllers to become available...
[joint_state_publisher-5] [INFO] [1750847237.374252180] [joint_state_publisher]: Waiting for robot_description to be published on the robot_description topic...
[rviz2-1] [INFO] [1750847237.419413243] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-1] [INFO] [1750847237.419499732] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-1] [INFO] [1750847237.429321396] [rviz2]: Stereo is NOT SUPPORTED
[ros2-8] [INFO] [1750847237.446501143] [spawner_fr3_arm_controller]: waiting for service /controller_manager/list_controllers to become available...
[ros2-9] [INFO] [1750847237.457682699] [spawner_joint_state_broadcaster]: waiting for service /controller_manager/list_controllers to become available...
[rviz2-1] Warning: class_loader.impl: SEVERE WARNING!!! A namespace collision has occurred with plugin factory for class rviz_default_plugins::displays::InteractiveMarkerDisplay. New factory will OVERWRITE existing one. This situation occurs when libraries containing plugins are directly linked against an executable (the one running right now generating this message). Please separate plugins out into their own library or just don't link against the library and use either class_loader::ClassLoader/MultiLibraryClassLoader to open.
[rviz2-1]          at line 253 in /opt/ros/humble/include/class_loader/class_loader/class_loader_core.hpp
[rviz2-1] [INFO] [1750847237.495271583] [moveit_rdf_loader.rdf_loader]: Loaded robot model in 0.0120809 seconds
[rviz2-1] [INFO] [1750847237.495295387] [moveit_robot_model.robot_model]: Loading robot model 'fr3'...
[rviz2-1] [WARN] [1750847237.495301198] [moveit_robot_model.robot_model]: Skipping virtual joint 'virtual_joint' because its child frame 'fr3_link0' does not match the URDF frame 'base'
[rviz2-1] [INFO] [1750847237.495303209] [moveit_robot_model.robot_model]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ERROR] [ros2_control_node-4]: process has died [pid 16036, exit code -6, cmd '/opt/ros/humble/lib/controller_manager/ros2_control_node --ros-args -r __ns:=/ --params-file /tmp/launch_params_apqby258 --params-file /home/v25/franka_ros2_ws/install/franka_fr3_moveit_config/share/franka_fr3_moveit_config/config/fr3_ros_controllers.yaml -r joint_states:=franka/joint_states'].
[INFO] [launch]: process[ros2_control_node-4] was required: shutting down launched system
[INFO] [ros2-9]: sending signal 'SIGINT' to process[ros2-9]
[INFO] [ros2-8]: sending signal 'SIGINT' to process[ros2-8]
[INFO] [franka_gripper_node-7]: sending signal 'SIGINT' to process[franka_gripper_node-7]
[INFO] [spawner-6]: sending signal 'SIGINT' to process[spawner-6]
[INFO] [joint_state_publisher-5]: sending signal 'SIGINT' to process[joint_state_publisher-5]
[INFO] [move_group-3]: sending signal 'SIGINT' to process[move_group-3]
[INFO] [robot_state_publisher-2]: sending signal 'SIGINT' to process[robot_state_publisher-2]
[INFO] [rviz2-1]: sending signal 'SIGINT' to process[rviz2-1]
[franka_gripper_node-7] [INFO] [1750847238.348693350] [rclcpp]: signal_handler(signum=2)
[move_group-3] [INFO] [1750847238.349856044] [rclcpp]: signal_handler(signum=2)
[robot_state_publisher-2] [INFO] [1750847238.350316480] [rclcpp]: signal_handler(signum=2)
[rviz2-1] [INFO] [1750847238.350937100] [rclcpp]: signal_handler(signum=2)
[rviz2-1] [ERROR] [1750847238.351037755] [moveit_ros_visualization.motion_planning_frame]: Action server: /recognize_objects not available
[rviz2-1] 
[rviz2-1] >>> [rcutils|error_handling.c:108] rcutils_set_error_state()
[rviz2-1] This error state is being overwritten:
[rviz2-1] 
[rviz2-1]   'rcl node's context is invalid, at ./src/rcl/node.c:428'
[rviz2-1] 
[rviz2-1] with this new error message:
[rviz2-1] 
[rviz2-1]   'the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at ./src/rcl/guard_condition.c:67'
[rviz2-1] 
[rviz2-1] rcutils_reset_error() should be called after error handling to avoid this.
[rviz2-1] <<<
[rviz2-1] [ERROR] [1750847238.354096469] [rviz2]: Could not load display config: failed to create guard condition: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at ./src/rcl/guard_condition.c:67
[move_group-3] [INFO] [1750847238.356304110] [moveit.ros_planning_interface.moveit_cpp]: Deleting MoveItCpp
[move_group-3] [INFO] [1750847238.356636099] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Stopped publishing maintained planning scene.
[move_group-3] [INFO] [1750847238.356869840] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Stopping world geometry monitor
[move_group-3] [INFO] [1750847238.356963261] [moveit_ros.planning_scene_monitor.planning_scene_monitor]: Stopping planning scene monitor
[move_group-3] Warning: class_loader.ClassLoader: SEVERE WARNING!!! Attempting to unload library while objects created by this loader exist in the heap! You should delete your objects before attempting to unload the library or destroying the ClassLoader. The library will NOT be unloaded.
[move_group-3]          at line 127 in ./src/class_loader.cpp
[move_group-3] Stack trace (most recent call last):
[move_group-3] #16   Object "", at 0xffffffffffffffff, in 
[move_group-3] #15   Object "/opt/ros/humble/lib/moveit_ros_move_group/move_group", at 0x64896571e724, in 
[move_group-3] #14   Source "../csu/libc-start.c", line 392, in __libc_start_main_impl [0x7461bad43e3f]
[move_group-3] #13   Source "../sysdeps/nptl/libc_start_call_main.h", line 58, in __libc_start_call_main [0x7461bad43d8f]
[move_group-3] #12   Object "/opt/ros/humble/lib/moveit_ros_move_group/move_group", at 0x64896571d65b, in 
[move_group-3] #11   Object "/opt/ros/humble/lib/moveit_ros_move_group/move_group", at 0x64896571f709, in 
[move_group-3] #10   Object "/opt/ros/humble/lib/libmoveit_cpp.so.2.5.9", at 0x7461bb6b9876, in moveit_cpp::MoveItCpp::~MoveItCpp()
[move_group-3] #9    Object "/opt/ros/humble/lib/libmoveit_cpp.so.2.5.9", at 0x7461bb6b7ba9, in 
[move_group-3] #8    Object "/opt/ros/humble/lib/libmoveit_trajectory_execution_manager.so.2.5.9", at 0x7461baa39495, in trajectory_execution_manager::TrajectoryExecutionManager::~TrajectoryExecutionManager()
[move_group-3] #7    Object "/opt/ros/humble/lib/libmoveit_trajectory_execution_manager.so.2.5.9", at 0x7461baa4c3a9, in 
[move_group-3] #6    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7461bb318b3c, in rclcpp::Node::~Node()
[move_group-3] #5    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7461bb318ade, in rclcpp::Node::~Node()
[move_group-3] #4    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7461bb2f3d49, in 
[move_group-3] #3    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7461bb322189, in 
[move_group-3] #2    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7461bb3220d0, in rclcpp::node_interfaces::NodeBase::~NodeBase()
[move_group-3] #1    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7461bb2f3d49, in 
[move_group-3] #0    Object "/opt/ros/humble/lib/librclcpp.so", at 0x7461bb2f8ac1, in rclcpp::CallbackGroup::~CallbackGroup()
[move_group-3] Segmentation fault (Address not mapped to object [0x746193c67798])
[INFO] [robot_state_publisher-2]: process has finished cleanly [pid 16032]
[INFO] [spawner-6]: process has finished cleanly [pid 16040]
[INFO] [joint_state_publisher-5]: process has finished cleanly [pid 16038]
[INFO] [franka_gripper_node-7]: process has finished cleanly [pid 16042]
[ERROR] [rviz2-1]: process has died [pid 16030, exit code -11, cmd '/opt/ros/humble/lib/rviz2/rviz2 -d /home/v25/franka_ros2_ws/install/franka_fr3_moveit_config/share/franka_fr3_moveit_config/rviz/moveit.rviz --ros-args -r __node:=rviz2 --params-file /tmp/launch_params_qfmf3w7t --params-file /tmp/launch_params_3_h3_2cd --params-file /tmp/launch_params_l02aaj8l --params-file /tmp/launch_params_z6dsvjur'].
[ERROR] [move_group-3]: process has died [pid 16034, exit code -11, cmd '/opt/ros/humble/lib/moveit_ros_move_group/move_group --ros-args -r __ns:=/ --params-file /tmp/launch_params_rp_manh7 --params-file /tmp/launch_params_xp4rlxb1 --params-file /tmp/launch_params_ee3ndz05 --params-file /tmp/launch_params_n50dfcdq --params-file /tmp/launch_params_b25z5w4e --params-file /tmp/launch_params_bbfqaju4 --params-file /tmp/launch_params_laio00sq'].
[move_group-3] 
[ERROR] [ros2-9]: process[ros2-9] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[ERROR] [ros2-8]: process[ros2-8] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
[INFO] [ros2-9]: sending signal 'SIGTERM' to process[ros2-9]
[INFO] [ros2-8]: sending signal 'SIGTERM' to process[ros2-8]
[ERROR] [ros2-9]: process has died [pid 16046, exit code -15, cmd 'ros2 run controller_manager spawner joint_state_broadcaster --controller-manager-timeout 60 --controller-manager controller_manager'].
[ERROR] [ros2-8]: process has died [pid 16044, exit code -15, cmd 'ros2 run controller_manager spawner fr3_arm_controller --controller-manager-timeout 60 --controller-manager controller_manager'].

**Comment by AndreasKuhner** [comment]
Hi @VaRuN-2509 ,
it still means that you are using the outdated franka_description. Did you checkout main of franka_description? Did you rebuild and re-source?

Cheers,
Andreas

**Comment by VaRuN-2509** [comment]
Yeah my bad, I thought I updated it bit it seems it wasn't.. now everything works fine.Thank you

**Comment by VaRuN-2509** [comment]
The change I did was
-> cd franka_description
-> git fetch
->git checkout 0.5.1

**Comment by bk-poudel** [comment]
Yes solved thank you very much
